version: '3.9'
services:
  resource-service-db:
    image: postgres:14-alpine
    env_file: resource-service.env
    ports:
      - 5433:5432
    volumes:
      - resource-service-db:/var/lib/postgresql/data/

  song-service-db:
    image: postgres:14-alpine
    env_file: song-service.env
    ports:
      - 5434:5432
    volumes:
      - song-service-db:/var/lib/postgresql/data/

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - 9093:9093
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    volumes:
      - kafka:/var/lib/kafka/data

  resource-service:
    image: microservices/resource-service:latest
    build:
      context: ../resource-service
    env_file: resource-service.env
    ports:
      - 8081:8081
    volumes:
      - ~/.aws/:/root/.aws:ro
    depends_on:
      - resource-service-db
      - kafka

  resource-processor:
    image: microservices/resource-processor:latest
    build:
      context: ../resource-processor
    environment:
      - resource_service_url=http://resource-service:8081
      - song_service_url=http://song-service:8082
      - KAFKA_HOST=kafka
      - KAFKA_PORT=9092
    ports:
      - 8080:8080
    depends_on:
      - resource-service
      - kafka

  song-service:
    image: microservices/song-service:latest
    build:
      context: ../song-service
    env_file: song-service.env
    ports:
      - 8082:8082
    depends_on:
      - song-service-db

volumes:
  resource-service-db:
  song-service-db:
  kafka:
