server:
  port: ${EUREKA_PORT:8761}
spring:
  application:
    name: eureka-discovery-service
eureka:
  instance:
    hostname: ${EUREKA_HOST:localhost}
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

logging:
  pattern:
    level: trace_id=%mdc{trace_id} span_id=%mdc{span_id} trace_flags=%mdc{trace_flags} %5p

management:
  metrics:
    enabled: true
    tags.application: ${spring.application.name}
