kafka:
  resource-topic: resource-upload
  bootstrap-address: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9093}

infrastructure:
  resource-service-id: resource-service
  song-service-id: song-service
  storage-service-id: storage-service

eureka:
  instance:
    hostname: ${RESOURCE_PROCESSOR_HOST:localhost}
    preferIpAddress: false
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/

spring:
  application:
    name: resource-processor