server:
  port: 9000
  error:
    include-message: always

spring:
  application:
    name: authorization-server
#  Custom security properties
  security:
    oauth2:
      client-uri: http://${CLIENT_HOST:127.0.0.1}:8084
      issuer-uri: http://${AUTHORIZATION_SERVER_HOST:auth-server}:${server.port}

eureka:
  instance:
    hostname: ${AUTHORIZATION_SERVER_HOST:localhost}
    preferIpAddress: false
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/

logging:
  level:
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
  pattern:
    level: trace_id=%mdc{trace_id} %5p

management:
  metrics:
    enabled: true
    tags:
      application: ${spring.application.name}