server:
  port: 8082
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:postgresql://${SONG_DB_HOST:localhost}:${SONG_DB_PORT:5434}/song-service-db
    username: root
    password: Initial0
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate.ddl-auto: update
  jackson:
    serialization:
      write-durations-as-timestamps: false
  application:
    name: song-service

eureka:
  instance:
    hostname: ${SONG_SERVICE_HOST:localhost}
    preferIpAddress: false
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/

logging:
  pattern:
    level: trace_id=%mdc{trace_id} %5p

management:
  metrics:
    enabled: true
    tags:
      application: ${spring.application.name}