server:
  port: 8082
  error:
    include-message: always


spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/song-service-db
    username: root
    password: Initial0
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
  jackson:
    serialization:
      write-durations-as-timestamps: false