server:
  port: ${API_GATEWAY_PORT:8090}

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway-service
  cloud:
    gateway:
      metrics:
        enabled: true
      routes:
        - id: resourceService
          uri: lb://RESOURCE-SERVICE
          predicates:
            - Path=/resources/**
        - id: songService
          uri: lb://SONG-SERVICE
          predicates:
            - Path=/songs/**
        - id: storageService
          uri: lb://STORAGE-SERVICE
          predicates:
            - Path=/storages/**
        - id: grafana
          uri: http://grafana:3000
          predicates:
            - Path=/grafana

management:
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
    metrics:
      enabled: true
    gateway:
      enabled: true # default value
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: metrics,info,health,prometheus,gateway
  health:
    diskspace.enabled: false

eureka:
  instance:
    hostname: ${API_GATEWAY_HOST:localhost}
    metadataMap:
      "prometheus.scrape": "true"
      "prometheus.path": "/actuator/prometheus"
      "prometheus.port": "8090"
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/

logging:
  pattern:
    level: trace_id=%mdc{trace_id} %5p
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
