server:
  port: ${API_GATEWAY_PORT:8090}

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: resourceService
          uri: lb://RESOURCE-SERVICE
          predicates:
            - Path=/resources/**
        - id: songService
          uri: lb://SONG-SERVICE
          predicates:
            - Path=/songs/**
eureka:
  instance:
    hostname: ${API_GATEWAY_HOST:localhost}
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
