server:
  port: 8081
  error:
    include-message: always

spring:
  application:
    name: resource-service
  datasource:
    url: jdbc:postgresql://${RESOURCE_DB_HOST:localhost}:${RESOURCE_DB_PORT:5433}/resource-service-db
    username: root
    password: Initial0
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

kafka:
  bootstrap-address: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9093}
  resource-topic: resource-upload

s3:
  bucket-name: pavel-shakhlovich-mp3
  region: eu-central-1

infrastructure:
  storage-service-id: storage-service

eureka:
  instance:
    hostname: ${RESOURCE_SERVICE_HOST:localhost}
    preferIpAddress: false
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health
    metadataMap:
      "prometheus.scrape": "true"
      "prometheus.path": "/actuator/prometheus"
      "prometheus.port": "8081"
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/

management:
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: metrics,info,health,prometheus
  health:
    diskspace.enabled: false
    circuitbreakers.enabled: true

resilience4j:
  circuitbreaker:
    circuitBreakerAspectOrder: 1
    instances:
      storage-client:
        registerHealthIndicator: true
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        slidingWindowSize: 3
        minimumNumberOfCalls: 3
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        eventConsumerBufferSize: 10
        recordExceptions:
          - com.pshakhlovich.microservices_fundamentals.resource.infrastructure.exception.InfrastructureException
        ignoreExceptions:
  retry:
    retryAspectOrder: 2
    instances:
      storage-client:
        maxAttempts: 3
        waitDuration: 1s
        retryExceptions:
          - com.pshakhlovich.microservices_fundamentals.resource.infrastructure.exception.InfrastructureException

logging:
  pattern:
    level: trace_id=%mdc{trace_id} %5p
