server:
  port: 8081
  error:
    include-message: always

spring:
  application:
    name: resource-service
  datasource:
    url: jdbc:postgresql://${RESOURCE_DB_HOST:localhost}:${RESOURCE_DB_PORT:5433}/resource-service-db
    username: root
    password: Initial0
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
  jpa:
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

kafka:
  bootstrap-address: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9093}
  resource-topic: resource-upload

s3:
  bucket-name: pavel-shakhlovich-mp3
  region: eu-central-1

eureka:
  instance:
    hostname: ${RESOURCE_SERVICE_HOST:localhost}
    preferIpAddress: false
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
