server:
  port: 8081
  error:
    include-message: always

spring:
  profiles:
    active: dev

kafka:
  resource-topic: resource-upload

s3:
  bucket-name: pavel-shakhlovich-mp3
  region: eu-central-1

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5433/resource-service-db
    username: root
    password: Initial0
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
  jpa:
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

kafka:
  bootstrap-address: localhost:9093
